# Generated by Django 5.2.10 on 2026-01-09 04:30

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20, verbose_name='股票代码')),
                ('date', models.DateField(db_index=True, verbose_name='日期')),
                ('open', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='开盘价')),
                ('high', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='最高价')),
                ('low', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='最低价')),
                ('close', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='收盘价')),
                ('volume', models.BigIntegerField(verbose_name='成交量')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='成交额')),
                ('adj_close', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='复权收盘价')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '股票日线数据',
                'verbose_name_plural': '股票日线数据',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['symbol', 'date'], name='quant_stock_symbol_5e2a71_idx')],
                'unique_together': {('symbol', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='策略名称')),
                ('strategy_type', models.CharField(choices=[('ma_cross', '均线交叉'), ('momentum', '动量策略'), ('mean_reversion', '均值回归'), ('breakout', '突破策略'), ('pair_trading', '配对交易'), ('grid', '网格交易'), ('custom', '自定义')], default='custom', max_length=20, verbose_name='策略类型')),
                ('description', models.TextField(blank=True, verbose_name='策略描述')),
                ('parameters', models.JSONField(default=dict, help_text='JSON格式的策略参数', verbose_name='策略参数')),
                ('symbols', models.JSONField(default=list, help_text='策略关注的股票代码列表', verbose_name='交易标的')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '运行中'), ('paused', '已暂停'), ('stopped', '已停止')], default='draft', max_length=20, verbose_name='状态')),
                ('initial_capital', models.DecimalField(decimal_places=2, default=Decimal('100000'), max_digits=15, verbose_name='初始资金')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所有者')),
            ],
            options={
                'verbose_name': '量化策略',
                'verbose_name_plural': '量化策略',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='BacktestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='回测名称')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(verbose_name='结束日期')),
                ('initial_capital', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='初始资金')),
                ('final_capital', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='最终资金')),
                ('total_return', models.DecimalField(decimal_places=4, help_text='百分比', max_digits=10, verbose_name='总收益率')),
                ('annual_return', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='年化收益率')),
                ('sharpe_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='夏普比率')),
                ('sortino_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='索提诺比率')),
                ('max_drawdown', models.DecimalField(decimal_places=4, help_text='百分比', max_digits=10, verbose_name='最大回撤')),
                ('max_drawdown_duration', models.IntegerField(blank=True, null=True, verbose_name='最大回撤持续天数')),
                ('win_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='胜率')),
                ('profit_factor', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='盈亏比')),
                ('total_trades', models.IntegerField(default=0, verbose_name='总交易次数')),
                ('winning_trades', models.IntegerField(default=0, verbose_name='盈利次数')),
                ('losing_trades', models.IntegerField(default=0, verbose_name='亏损次数')),
                ('avg_trade_return', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='平均每笔收益')),
                ('trades_data', models.JSONField(default=list, help_text='交易对列表', verbose_name='交易明细')),
                ('equity_curve', models.JSONField(default=list, help_text='每日净值数据', verbose_name='权益曲线')),
                ('parameters_used', models.JSONField(default=dict, verbose_name='使用的参数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backtest_results', to='quant.strategy', verbose_name='策略')),
            ],
            options={
                'verbose_name': '回测结果',
                'verbose_name_plural': '回测结果',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TradeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('backtest', '回测'), ('paper', '模拟'), ('live', '实盘')], default='backtest', max_length=20, verbose_name='交易模式')),
                ('symbol', models.CharField(db_index=True, max_length=20, verbose_name='股票代码')),
                ('order_type', models.CharField(choices=[('market', '市价单'), ('limit', '限价单'), ('stop', '止损单'), ('stop_limit', '止损限价单')], default='market', max_length=20, verbose_name='订单类型')),
                ('side', models.CharField(choices=[('buy', '买入'), ('sell', '卖出')], max_length=10, verbose_name='方向')),
                ('quantity', models.IntegerField(verbose_name='委托数量')),
                ('price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='委托价格')),
                ('filled_quantity', models.IntegerField(default=0, verbose_name='成交数量')),
                ('filled_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='成交均价')),
                ('commission', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='手续费')),
                ('slippage', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10, verbose_name='滑点')),
                ('status', models.CharField(choices=[('pending', '待提交'), ('submitted', '已提交'), ('partial', '部分成交'), ('filled', '已成交'), ('cancelled', '已取消'), ('rejected', '已拒绝')], default='pending', max_length=20, verbose_name='状态')),
                ('signal_time', models.DateTimeField(blank=True, null=True, verbose_name='信号时间')),
                ('order_time', models.DateTimeField(blank=True, null=True, verbose_name='委托时间')),
                ('filled_time', models.DateTimeField(blank=True, null=True, verbose_name='成交时间')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='交易原因')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('backtest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='quant.backtestresult', verbose_name='回测')),
                ('strategy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='quant.strategy', verbose_name='策略')),
            ],
            options={
                'verbose_name': '委托单',
                'verbose_name_plural': '委托单',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['symbol', 'status'], name='quant_trade_symbol_0d770f_idx'), models.Index(fields=['strategy', 'created_at'], name='quant_trade_strateg_468022_idx')],
            },
        ),
    ]
