# Generated by Django 5.2.10 on 2026-01-07 10:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='账户名称')),
                ('account_type', models.CharField(choices=[('stock', '股票'), ('futures', '期货'), ('forex', '外汇'), ('crypto', '加密货币'), ('options', '期权')], max_length=20, verbose_name='账户类型')),
                ('broker', models.CharField(blank=True, max_length=100, verbose_name='券商/交易所')),
                ('account_id', models.CharField(blank=True, max_length=100, verbose_name='账户ID')),
                ('initial_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='初始资金')),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='当前余额')),
                ('available_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='可用余额')),
                ('status', models.CharField(choices=[('active', '活跃'), ('inactive', '未激活'), ('frozen', '冻结'), ('closed', '已关闭')], default='active', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trading_accounts', to=settings.AUTH_USER_MODEL, verbose_name='所有者')),
            ],
            options={
                'verbose_name': '交易账户',
                'verbose_name_plural': '交易账户',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='策略名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='策略代码')),
                ('description', models.TextField(blank=True, verbose_name='策略描述')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '运行中'), ('paused', '暂停'), ('stopped', '已停止'), ('archived', '已归档')], default='draft', max_length=20, verbose_name='状态')),
                ('risk_level', models.CharField(default='medium', help_text='low/medium/high', max_length=20, verbose_name='风险等级')),
                ('max_position_size', models.DecimalField(decimal_places=2, default=100, help_text='最大仓位百分比', max_digits=10, verbose_name='最大仓位')),
                ('stop_loss_ratio', models.DecimalField(decimal_places=2, default=5.0, help_text='止损百分比', max_digits=5, verbose_name='止损比例')),
                ('take_profit_ratio', models.DecimalField(decimal_places=2, default=10.0, help_text='止盈百分比', max_digits=5, verbose_name='止盈比例')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建���间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='strategies', to='trading.account', verbose_name='关联账户')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategies', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '交易策略',
                'verbose_name_plural': '交易策略',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_trades', models.IntegerField(default=0, verbose_name='总交易次数')),
                ('profitable_trades', models.IntegerField(default=0, verbose_name='盈利次数')),
                ('losing_trades', models.IntegerField(default=0, verbose_name='亏损次数')),
                ('win_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='胜率')),
                ('total_profit', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='总盈利')),
                ('total_loss', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='总亏损')),
                ('profit_factor', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='盈亏比')),
                ('average_profit', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='平均盈利')),
                ('average_loss', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='平均亏损')),
                ('largest_profit', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='最大盈利')),
                ('largest_loss', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='最大亏损')),
                ('max_drawdown', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='最大回撤')),
                ('max_drawdown_ratio', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='最大回撤比例')),
                ('sharpe_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='夏普比率')),
                ('sortino_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='索提诺比率')),
                ('calmar_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='卡玛比率')),
                ('total_return', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='总收益率')),
                ('annualized_return', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='年化收益率')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('strategy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='performance_metrics', to='trading.strategy', verbose_name='策略')),
            ],
            options={
                'verbose_name': '绩效指标',
                'verbose_name_plural': '绩效指标',
            },
        ),
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(db_index=True, verbose_name='报表日期')),
                ('starting_balance', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='期初余额')),
                ('ending_balance', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='期末余额')),
                ('net_deposit', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='净入金')),
                ('profit_loss', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='当日盈亏')),
                ('profit_loss_ratio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='当日盈亏比例')),
                ('trade_count', models.IntegerField(default=0, verbose_name='交易次数')),
                ('win_count', models.IntegerField(default=0, verbose_name='盈利次数')),
                ('loss_count', models.IntegerField(default=0, verbose_name='亏损次数')),
                ('win_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='胜率')),
                ('max_drawdown', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='最大回撤')),
                ('commission', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='手续费')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to='trading.account', verbose_name='账户')),
            ],
            options={
                'verbose_name': '每日报表',
                'verbose_name_plural': '每日报表',
                'ordering': ['-report_date'],
                'unique_together': {('account', 'report_date')},
            },
        ),
        migrations.CreateModel(
            name='MonthlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='年份')),
                ('month', models.IntegerField(verbose_name='月份')),
                ('starting_balance', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='期初余额')),
                ('ending_balance', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='期末余额')),
                ('net_deposit', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='净入金')),
                ('profit_loss', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='月度盈亏')),
                ('profit_loss_ratio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='月度盈亏比例')),
                ('trade_count', models.IntegerField(default=0, verbose_name='交易次数')),
                ('win_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='胜率')),
                ('max_drawdown', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='最大回撤')),
                ('sharpe_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='夏普比率')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_reports', to='trading.account', verbose_name='账户')),
            ],
            options={
                'verbose_name': '月度报表',
                'verbose_name_plural': '月度报表',
                'ordering': ['-year', '-month'],
                'unique_together': {('account', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=50, verbose_name='交易标的')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='持仓数量')),
                ('avg_price', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='平均成本')),
                ('current_price', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='当前价格')),
                ('market_value', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='市值')),
                ('profit_loss', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='盈亏')),
                ('profit_loss_ratio', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='盈亏比例')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='trading.account', verbose_name='账户')),
            ],
            options={
                'verbose_name': '持仓',
                'verbose_name_plural': '持仓',
                'ordering': ['-market_value'],
                'unique_together': {('account', 'symbol')},
            },
        ),
        migrations.CreateModel(
            name='TradeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=50, verbose_name='交易标的')),
                ('side', models.CharField(choices=[('buy', '买入'), ('sell', '卖出')], max_length=10, verbose_name='方向')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='数量')),
                ('price', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='价格')),
                ('executed_price', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='成交价')),
                ('status', models.CharField(choices=[('pending', '待成交'), ('filled', '已成交'), ('partially_filled', '部分成交'), ('cancelled', '已取消'), ('rejected', '已拒绝')], default='pending', max_length=20, verbose_name='状态')),
                ('order_id', models.CharField(max_length=100, unique=True, verbose_name='订单ID')),
                ('commission', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='手续费')),
                ('slippage', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='滑点')),
                ('profit_loss', models.DecimalField(decimal_places=2, default=0, help_text='已实现盈亏', max_digits=15, verbose_name='盈亏')),
                ('trade_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='交易时间')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_logs', to='trading.account', verbose_name='账户')),
                ('strategy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trade_logs', to='trading.strategy', verbose_name='策略')),
            ],
            options={
                'verbose_name': '交易日志',
                'verbose_name_plural': '交易日志',
                'ordering': ['-trade_time'],
                'indexes': [models.Index(fields=['symbol', '-trade_time'], name='trading_tra_symbol_763187_idx'), models.Index(fields=['account', '-trade_time'], name='trading_tra_account_1b1ebf_idx')],
            },
        ),
    ]
