# Generated by Django 5.2.10 on 2026-01-08 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_remove_strategy_code_alter_strategy_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strategy',
            name='max_position_size',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='risk_level',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='stop_loss_ratio',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='take_profit_ratio',
        ),
    ]
