# Generated by Django 5.2.10 on 2026-01-08 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0003_remove_strategy_max_position_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strategy',
            name='account',
        ),
    ]
