# Generated by Django 5.2.10 on 2026-01-08 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0004_remove_strategy_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='例如：苹果公司、沪深300指数期货', max_length=100, verbose_name='标的名称')),
                ('code', models.CharField(help_text='例如：AAPL、IF2401', max_length=50, unique=True, verbose_name='标的代码')),
                ('symbol_type', models.CharField(choices=[('stock', '股票'), ('futures', '期货'), ('forex', '外汇'), ('crypto', '加密货币'), ('index', '指数'), ('commodity', '商品'), ('bond', '债券'), ('etf', 'ETF')], max_length=20, verbose_name='标的类型')),
                ('exchange', models.CharField(blank=True, help_text='例如：上期所、CME、NYSE', max_length=100, verbose_name='交易所')),
                ('currency', models.CharField(default='CNY', help_text='例如：CNY、USD、EUR', max_length=10, verbose_name='计价货币')),
                ('contract_size', models.DecimalField(decimal_places=4, default=1, help_text='每点代表的价值，例如：股指期货300，黄金期货1000', max_digits=15, verbose_name='合约乘数')),
                ('minimum_tick', models.DecimalField(decimal_places=4, default=0.01, help_text='价格波动的最小单位', max_digits=10, verbose_name='最小变动价位')),
                ('margin_rate', models.DecimalField(blank=True, decimal_places=4, help_text='期货保证金比例，例如：0.15表示15%', max_digits=10, null=True, verbose_name='保证金比例')),
                ('commission_rate', models.DecimalField(blank=True, decimal_places=6, help_text='手续费比例，例如：0.0001表示万分之一', max_digits=10, null=True, verbose_name='手续费率')),
                ('commission_per_contract', models.DecimalField(decimal_places=2, default=0, help_text='固定手续费，每手多少元', max_digits=10, verbose_name='每手手续费')),
                ('is_active', models.BooleanField(default=True, help_text='是否可交易', verbose_name='是否活跃')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '交易标的',
                'verbose_name_plural': '交易标的',
                'ordering': ['symbol_type', 'code'],
            },
        ),
        migrations.RemoveIndex(
            model_name='tradelog',
            name='trading_tra_symbol_763187_idx',
        ),
        migrations.AlterField(
            model_name='position',
            name='symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='trading.symbol', verbose_name='交易标的'),
        ),
        migrations.AlterField(
            model_name='tradelog',
            name='symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trade_logs', to='trading.symbol', verbose_name='交易标的'),
        ),
        migrations.AddIndex(
            model_name='tradelog',
            index=models.Index(fields=['-trade_time'], name='trading_tra_trade_t_a4ffd6_idx'),
        ),
    ]
