# Generated by Django 5.2.10 on 2026-01-08 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0005_symbol_remove_tradelog_trading_tra_symbol_763187_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='trade_images/%Y/%m/%d/', verbose_name='截图')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='描述')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('trade_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='trading.tradelog', verbose_name='交易日志')),
            ],
            options={
                'verbose_name': '交易截图',
                'verbose_name_plural': '交易截图',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
