# Generated by Django 5.2.10 on 2026-01-08 02:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0006_tradeimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('deposit', '入金'), ('withdraw', '出金'), ('trade_profit', '交易盈利'), ('trade_loss', '交易亏损'), ('commission', '手续费'), ('dividend', '分红'), ('interest', '利息'), ('adjustment', '调整')], max_length=20, verbose_name='交易类型')),
                ('amount', models.DecimalField(decimal_places=2, help_text='正数表示增加，负数表示减少', max_digits=15, verbose_name='金额')),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='变动前余额')),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='变动后余额')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='描述')),
                ('transaction_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='交易时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='trading.account', verbose_name='账户')),
                ('trade_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='trading.tradelog', verbose_name='关联交易')),
            ],
            options={
                'verbose_name': '账户流水',
                'verbose_name_plural': '账户流水',
                'ordering': ['-transaction_time'],
                'indexes': [models.Index(fields=['account', '-transaction_time'], name='trading_acc_account_df4559_idx')],
            },
        ),
    ]
