# Generated by Django 5.2.10 on 2026-01-09 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0007_accounttransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotion_before', models.CharField(blank=True, choices=[('calm', '冷静'), ('confident', '自信'), ('anxious', '焦虑'), ('fearful', '恐惧'), ('greedy', '贪婪'), ('fomo', 'FOMO'), ('revenge', '报复心态'), ('euphoric', '狂喜'), ('frustrated', '沮丧'), ('neutral', '平静')], help_text='下单前的情绪状态', max_length=20, verbose_name='交易前情绪')),
                ('emotion_after', models.CharField(blank=True, choices=[('calm', '冷静'), ('confident', '自信'), ('anxious', '焦虑'), ('fearful', '恐惧'), ('greedy', '贪婪'), ('fomo', 'FOMO'), ('revenge', '报复心态'), ('euphoric', '狂喜'), ('frustrated', '沮丧'), ('neutral', '平静')], help_text='平仓后的情绪状态', max_length=20, verbose_name='交易后情绪')),
                ('tags', models.CharField(blank=True, help_text='可选多个标签，用逗号分隔', max_length=500, verbose_name='复盘标签')),
                ('execution_score', models.IntegerField(blank=True, choices=[(1, '1分 - 严重失误'), (2, '2分 - 较差'), (3, '3分 - 一般'), (4, '4分 - 良好'), (5, '5分 - 优秀')], help_text='对本次交易执行的整体评分', null=True, verbose_name='执行评分')),
                ('entry_reason', models.TextField(blank=True, help_text='为什么在这个位置入场', verbose_name='入场理由')),
                ('exit_reason', models.TextField(blank=True, help_text='为什么在这个位置出场', verbose_name='出场理由')),
                ('what_went_well', models.TextField(blank=True, verbose_name='做得好的地方')),
                ('what_went_wrong', models.TextField(blank=True, verbose_name='做得不好的地方')),
                ('lessons_learned', models.TextField(blank=True, help_text='这笔交易学到了什么', verbose_name='经验教训')),
                ('improvement_plan', models.TextField(blank=True, help_text='下次如何改进', verbose_name='改进计划')),
                ('market_condition', models.CharField(blank=True, help_text='如：震荡、单边上涨、单边下跌', max_length=100, verbose_name='市场环境')),
                ('followed_plan', models.BooleanField(blank=True, help_text='本次交易是否按照交易计划执行', null=True, verbose_name='是否遵守计划')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('trade_log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='trading.tradelog', verbose_name='交易记录')),
            ],
            options={
                'verbose_name': '交易复盘',
                'verbose_name_plural': '交易复盘',
                'ordering': ['-created_at'],
            },
        ),
    ]
