# Generated by Django 5.2.10 on 2026-01-09 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0008_tradereview'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='规则名称')),
                ('rule_type', models.CharField(choices=[('daily_loss_limit', '每日亏损限额'), ('single_trade_loss', '单笔亏损限额'), ('max_drawdown', '最大回撤'), ('max_position_ratio', '最大仓位比例'), ('consecutive_losses', '连续亏损次数'), ('daily_trade_limit', '每日交易次数'), ('max_leverage', '最大杠杆')], max_length=30, verbose_name='规则类型')),
                ('threshold_value', models.DecimalField(decimal_places=2, help_text='根据规则类型：金额、比例(%)或次数', max_digits=15, verbose_name='阈值')),
                ('threshold_percent', models.DecimalField(blank=True, decimal_places=2, help_text='相对于账户资金的比例，如 2 表示 2%', max_digits=5, null=True, verbose_name='阈值比例')),
                ('action', models.CharField(choices=[('alert', '发送警告'), ('block', '阻止交易'), ('reduce', '强制减仓')], default='alert', max_length=20, verbose_name='触发动作')),
                ('level', models.CharField(choices=[('warning', '警告'), ('danger', '危险'), ('critical', '严重')], default='warning', max_length=20, verbose_name='警告级别')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_rules', to='trading.account', verbose_name='账户')),
            ],
            options={
                'verbose_name': '风险规则',
                'verbose_name_plural': '风险规则',
                'ordering': ['account', 'rule_type'],
                'unique_together': {('account', 'rule_type', 'level')},
            },
        ),
        migrations.CreateModel(
            name='RiskAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('daily_loss_limit', '每日亏损限额'), ('single_trade_loss', '单笔亏损限额'), ('max_drawdown', '最大回撤'), ('max_position_ratio', '最大仓位比例'), ('consecutive_losses', '连续亏损次数'), ('daily_trade_limit', '每日交易次数'), ('max_leverage', '最大杠杆')], max_length=30, verbose_name='警告类型')),
                ('level', models.CharField(choices=[('warning', '警告'), ('danger', '危险'), ('critical', '严重')], max_length=20, verbose_name='警告级别')),
                ('title', models.CharField(max_length=200, verbose_name='警告标题')),
                ('message', models.TextField(verbose_name='警告详情')),
                ('current_value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='当前值')),
                ('threshold_value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='阈值')),
                ('status', models.CharField(choices=[('active', '活跃'), ('acknowledged', '已确认'), ('resolved', '已解决'), ('ignored', '已忽略')], default='active', max_length=20, verbose_name='状态')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='解决时间')),
                ('triggered_at', models.DateTimeField(auto_now_add=True, verbose_name='触发时间')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_alerts', to='trading.account', verbose_name='账户')),
                ('trade_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_alerts', to='trading.tradelog', verbose_name='关联交易')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='trading.riskrule', verbose_name='触发规则')),
            ],
            options={
                'verbose_name': '风险警告',
                'verbose_name_plural': '风险警告',
                'ordering': ['-triggered_at'],
                'indexes': [models.Index(fields=['account', '-triggered_at'], name='trading_ris_account_77035d_idx'), models.Index(fields=['status', '-triggered_at'], name='trading_ris_status_60b42c_idx')],
            },
        ),
        migrations.CreateModel(
            name='RiskSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(db_index=True, verbose_name='快照日期')),
                ('daily_pnl', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='当日盈亏')),
                ('daily_pnl_percent', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='当日盈亏比例')),
                ('daily_trade_count', models.IntegerField(default=0, verbose_name='当日交易次数')),
                ('daily_win_count', models.IntegerField(default=0, verbose_name='当日盈利次数')),
                ('daily_loss_count', models.IntegerField(default=0, verbose_name='当日亏损次数')),
                ('consecutive_wins', models.IntegerField(default=0, verbose_name='连续盈利次数')),
                ('consecutive_losses', models.IntegerField(default=0, verbose_name='连续亏损次数')),
                ('peak_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='历史最高余额')),
                ('current_drawdown', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='当前回撤')),
                ('current_drawdown_percent', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='当前回撤比例')),
                ('max_drawdown', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='最大回撤')),
                ('max_drawdown_percent', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='最大回撤比例')),
                ('total_position_value', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='持仓总值')),
                ('position_ratio', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='仓位比例')),
                ('risk_score', models.IntegerField(default=0, help_text='0-100，越高风险越大', verbose_name='风险评分')),
                ('active_alerts_count', models.IntegerField(default=0, verbose_name='活跃警告数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_snapshots', to='trading.account', verbose_name='账户')),
            ],
            options={
                'verbose_name': '风险快照',
                'verbose_name_plural': '风险快照',
                'ordering': ['-snapshot_date'],
                'unique_together': {('account', 'snapshot_date')},
            },
        ),
    ]
