# Generated by Django 5.2.10 on 2026-01-09 03:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0009_riskrule_riskalert_risksnapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchlistGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='分组名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('color', models.CharField(default='#3B82F6', help_text='十六进制颜色代码，如 #3B82F6', max_length=20, verbose_name='颜色标记')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_groups', to=settings.AUTH_USER_MODEL, verbose_name='所有者')),
            ],
            options={
                'verbose_name': '观察分组',
                'verbose_name_plural': '观察分组',
                'ordering': ['sort_order', 'name'],
                'unique_together': {('owner', 'name')},
            },
        ),
        migrations.CreateModel(
            name='DailyNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_date', models.DateField(db_index=True, verbose_name='日期')),
                ('pre_market_plan', models.TextField(blank=True, help_text='今日交易计划、关注标的、重要事件', verbose_name='盘前计划')),
                ('market_outlook', models.CharField(blank=True, choices=[('bullish', '看多'), ('bearish', '看空'), ('neutral', '中性'), ('uncertain', '不确定')], max_length=20, verbose_name='市场展望')),
                ('focus_sectors', models.CharField(blank=True, max_length=200, verbose_name='关注板块')),
                ('key_events', models.TextField(blank=True, help_text='财报、经济数据、政策等', verbose_name='重要事件')),
                ('post_market_summary', models.TextField(blank=True, verbose_name='盘后总结')),
                ('lessons_learned', models.TextField(blank=True, verbose_name='经验教训')),
                ('mood', models.CharField(blank=True, choices=[('great', '很好'), ('good', '不错'), ('normal', '一般'), ('bad', '不好'), ('terrible', '很差')], max_length=20, verbose_name='今日心情')),
                ('planned_trades', models.IntegerField(default=0, verbose_name='计划交易数')),
                ('executed_trades', models.IntegerField(default=0, verbose_name='执行交易数')),
                ('followed_plan_count', models.IntegerField(default=0, verbose_name='遵守计划数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_notes', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '每日笔记',
                'verbose_name_plural': '每日笔记',
                'ordering': ['-note_date'],
                'unique_together': {('owner', 'note_date')},
            },
        ),
        migrations.CreateModel(
            name='TradePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('daily', '日计划'), ('weekly', '周计划'), ('swing', '波段计划'), ('position', '持仓计划')], default='daily', max_length=20, verbose_name='计划类型')),
                ('direction', models.CharField(choices=[('long', '做多'), ('short', '做空'), ('both', '双向')], default='long', max_length=10, verbose_name='方向')),
                ('plan_date', models.DateField(db_index=True, verbose_name='计划日期')),
                ('valid_until', models.DateField(blank=True, help_text='留空表示仅当日有效', null=True, verbose_name='有效期至')),
                ('entry_price_min', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='入场价下限')),
                ('entry_price_max', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='入场价上限')),
                ('entry_condition', models.TextField(blank=True, help_text='描述满足什么条件时入场', verbose_name='入场条件')),
                ('stop_loss', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='止损价')),
                ('take_profit_1', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='止盈1')),
                ('take_profit_2', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='止盈2')),
                ('take_profit_3', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='止盈3')),
                ('exit_condition', models.TextField(blank=True, help_text='描述满足什么条件时出场', verbose_name='出场条件')),
                ('planned_quantity', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='计划数量')),
                ('max_risk_amount', models.DecimalField(decimal_places=2, help_text='本计划允许的最大亏损', max_digits=15, verbose_name='最大风险金额')),
                ('position_size_percent', models.DecimalField(blank=True, decimal_places=2, help_text='占账户资金的百分比', max_digits=5, null=True, verbose_name='仓位比例')),
                ('analysis', models.TextField(blank=True, help_text='技术面/基本面分析', verbose_name='分析理由')),
                ('key_levels', models.CharField(blank=True, help_text='支撑位/阻力位，用逗号分隔', max_length=200, verbose_name='关键价位')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending', '待执行'), ('partial', '部分执行'), ('executed', '已执行'), ('cancelled', '已取消'), ('expired', '已过期')], default='draft', max_length=20, verbose_name='状态')),
                ('executed_at', models.DateTimeField(blank=True, null=True, verbose_name='执行时间')),
                ('execution_notes', models.TextField(blank=True, verbose_name='执行备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_plans', to='trading.account', verbose_name='账户')),
                ('executed_trade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_plan', to='trading.tradelog', verbose_name='执行交易')),
                ('strategy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trade_plans', to='trading.strategy', verbose_name='策略')),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_plans', to='trading.symbol', verbose_name='标的')),
            ],
            options={
                'verbose_name': '交易计划',
                'verbose_name_plural': '交易计划',
                'ordering': ['-plan_date', '-created_at'],
                'indexes': [models.Index(fields=['account', '-plan_date'], name='trading_tra_account_f6afa7_idx'), models.Index(fields=['status', '-plan_date'], name='trading_tra_status_7c0bee_idx')],
            },
        ),
        migrations.CreateModel(
            name='WatchlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_price', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='目标价格')),
                ('alert_price_above', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='价格上破提醒')),
                ('alert_price_below', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='价格下破提醒')),
                ('priority', models.IntegerField(choices=[(1, '低'), (2, '中'), (3, '高'), (4, '紧急')], default=2, verbose_name='优先级')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('tags', models.CharField(blank=True, help_text='用逗号分隔多个标签', max_length=200, verbose_name='标签')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否活跃')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='trading.watchlistgroup', verbose_name='分组')),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_items', to='trading.symbol', verbose_name='标的')),
            ],
            options={
                'verbose_name': '观察项目',
                'verbose_name_plural': '观察项目',
                'ordering': ['-priority', '-updated_at'],
                'unique_together': {('group', 'symbol')},
            },
        ),
    ]
