# Generated by Django 5.2.10 on 2026-01-09 03:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0010_watchlistgroup_dailynote_tradeplan_watchlistitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_price_alert', models.BooleanField(default=True, verbose_name='价格提醒')),
                ('enable_plan_reminder', models.BooleanField(default=True, verbose_name='计划提醒')),
                ('enable_risk_warning', models.BooleanField(default=True, verbose_name='风险警告')),
                ('enable_daily_summary', models.BooleanField(default=True, verbose_name='每日总结')),
                ('enable_trade_notification', models.BooleanField(default=True, verbose_name='交易通知')),
                ('daily_summary_time', models.TimeField(default='20:00', verbose_name='每日总结提醒时间')),
                ('plan_reminder_minutes', models.IntegerField(default=30, verbose_name='计划提前提醒(分钟)')),
                ('quiet_hours_start', models.TimeField(blank=True, null=True, verbose_name='静默开始时间')),
                ('quiet_hours_end', models.TimeField(blank=True, null=True, verbose_name='静默结束时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_setting', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '通知设置',
                'verbose_name_plural': '通知设置',
            },
        ),
        migrations.CreateModel(
            name='PriceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(choices=[('above', '高于'), ('below', '低于'), ('cross_up', '向上穿越'), ('cross_down', '向下穿越')], max_length=20, verbose_name='条件')),
                ('target_price', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='目标价格')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='有效期至')),
                ('trigger_once', models.BooleanField(default=True, help_text='触发后自动取消，否则会重复提醒', verbose_name='仅触发一次')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='备注')),
                ('status', models.CharField(choices=[('active', '监控中'), ('triggered', '已触发'), ('cancelled', '已取消'), ('expired', '已过期')], default='active', max_length=20, verbose_name='状态')),
                ('last_price', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='最后检查价格')),
                ('triggered_at', models.DateTimeField(blank=True, null=True, verbose_name='触发时间')),
                ('trigger_count', models.IntegerField(default=0, verbose_name='触发次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_alerts', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_alerts', to='trading.symbol', verbose_name='标的')),
            ],
            options={
                'verbose_name': '价格提醒',
                'verbose_name_plural': '价格提醒',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('price_alert', '价格提醒'), ('plan_reminder', '计划提醒'), ('risk_warning', '风险警告'), ('daily_summary', '每日总结'), ('trade_executed', '交易执行'), ('system', '系统通知')], max_length=20, verbose_name='通知类型')),
                ('priority', models.CharField(choices=[('low', '低'), ('normal', '普通'), ('high', '高'), ('urgent', '紧急')], default='normal', max_length=20, verbose_name='优先级')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('message', models.TextField(verbose_name='内容')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='额外数据')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='阅读时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('related_alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='trading.riskalert', verbose_name='相关警告')),
                ('related_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='trading.tradeplan', verbose_name='相关计划')),
                ('related_symbol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='trading.symbol', verbose_name='相关标的')),
                ('related_trade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='trading.tradelog', verbose_name='相关交易')),
            ],
            options={
                'verbose_name': '通知消息',
                'verbose_name_plural': '通知消息',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner', '-created_at'], name='trading_not_owner_i_78b1ee_idx'), models.Index(fields=['owner', 'is_read', '-created_at'], name='trading_not_owner_i_683075_idx')],
            },
        ),
    ]
