# Generated by Django 5.2.10 on 2026-01-09 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0011_notification_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.CharField(choices=[('active', '活跃'), ('inactive', '未激活'), ('frozen', '冻结'), ('closed', '已关闭')], db_index=True, default='active', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('active', '运行中'), ('paused', '暂停'), ('stopped', '已停止'), ('archived', '已归档')], db_index=True, default='draft', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='tradelog',
            name='status',
            field=models.CharField(choices=[('pending', '待成交'), ('filled', '已成交'), ('partially_filled', '部分成交'), ('cancelled', '已取消'), ('rejected', '已拒绝')], db_index=True, default='pending', max_length=20, verbose_name='状态'),
        ),
    ]
