# Generated by Django 5.2.10 on 2026-01-09 07:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0012_add_status_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tradelog',
            name='close_time',
            field=models.DateTimeField(blank=True, help_text='平仓时间', null=True, verbose_name='平仓时间'),
        ),
        migrations.AddField(
            model_name='tradelog',
            name='holding_minutes',
            field=models.IntegerField(blank=True, help_text='自动计算', null=True, verbose_name='持仓分钟数'),
        ),
        migrations.AddField(
            model_name='tradelog',
            name='open_time',
            field=models.DateTimeField(blank=True, help_text='建仓时间', null=True, verbose_name='开仓时间'),
        ),
        migrations.CreateModel(
            name='TradeTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='标签名称')),
                ('category', models.CharField(choices=[('entry', '入场类型'), ('exit', '出场类型'), ('market', '市场环境'), ('pattern', '形态'), ('custom', '自定义')], default='custom', max_length=20, verbose_name='标签分类')),
                ('color', models.CharField(default='#3B82F6', help_text='十六进制颜色代码', max_length=20, verbose_name='颜色')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='描述')),
                ('is_system', models.BooleanField(default=False, help_text='系统预设标签', verbose_name='系统标签')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_tags', to=settings.AUTH_USER_MODEL, verbose_name='所有者')),
            ],
            options={
                'verbose_name': '交易标签',
                'verbose_name_plural': '交易标签',
                'ordering': ['category', 'name'],
                'unique_together': {('owner', 'name')},
            },
        ),
        migrations.AddField(
            model_name='tradelog',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='trade_logs', to='trading.tradetag', verbose_name='交易标签'),
        ),
    ]
