# Generated by Django 5.2.10 on 2026-01-09 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0013_add_trade_tags_and_holding_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricealert',
            name='alert_type',
            field=models.CharField(choices=[('price', '价格提醒'), ('stop_loss', '止损提醒'), ('take_profit', '止盈提醒')], default='price', max_length=20, verbose_name='提醒类型'),
        ),
        migrations.AddField(
            model_name='pricealert',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='trading.position', verbose_name='关联持仓'),
        ),
    ]
