# Generated by Django 5.2.10 on 2026-01-09 08:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0014_add_alert_type_and_position'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='报告名称')),
                ('report_type', models.CharField(choices=[('trade_summary', '交易总结'), ('performance', '绩效报告'), ('risk_report', '风险报告')], max_length=20, verbose_name='报告类型')),
                ('frequency', models.CharField(choices=[('daily', '每日'), ('weekly', '每周'), ('monthly', '每月')], max_length=20, verbose_name='频率')),
                ('send_time', models.TimeField(default='08:00', verbose_name='发送时间')),
                ('send_day', models.IntegerField(default=1, help_text='每周几(1-7)或每月几号(1-31)', verbose_name='发送日')),
                ('email', models.EmailField(max_length=254, verbose_name='接收邮箱')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('last_sent', models.DateTimeField(blank=True, null=True, verbose_name='最后发送时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_reports', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '定时报告',
                'verbose_name_plural': '定时报告',
            },
        ),
        migrations.CreateModel(
            name='StrategySignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy_name', models.CharField(max_length=100, verbose_name='策略名称')),
                ('symbol', models.CharField(max_length=20, verbose_name='标的代码')),
                ('signal_type', models.CharField(choices=[('buy', '买入信号'), ('sell', '卖出信号'), ('hold', '持有')], max_length=10, verbose_name='信号类型')),
                ('source', models.CharField(choices=[('backtest', '回测'), ('live', '实盘'), ('webhook', 'Webhook')], max_length=20, verbose_name='来源')),
                ('price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='信号价格')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='建议数量')),
                ('reason', models.TextField(blank=True, verbose_name='信号原因')),
                ('extra_data', models.JSONField(default=dict, verbose_name='附加数据')),
                ('is_notified', models.BooleanField(default=False, verbose_name='已通知')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategy_signals', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '策略信号',
                'verbose_name_plural': '策略信号',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('webhook_type', models.CharField(choices=[('inbound', '接收信号'), ('outbound', '发送通知')], max_length=20, verbose_name='类型')),
                ('url', models.URLField(blank=True, help_text='outbound类型需要填写', verbose_name='URL地址')),
                ('secret_key', models.CharField(max_length=64, unique=True, verbose_name='密钥')),
                ('status', models.CharField(choices=[('active', '启用'), ('inactive', '停用')], default='active', max_length=20, verbose_name='状态')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('last_triggered', models.DateTimeField(blank=True, null=True, verbose_name='最后触发时间')),
                ('trigger_count', models.IntegerField(default=0, verbose_name='触发次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'Webhook',
                'verbose_name_plural': 'Webhook',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(max_length=10, verbose_name='方向')),
                ('payload', models.JSONField(default=dict, verbose_name='数据')),
                ('response_code', models.IntegerField(blank=True, null=True, verbose_name='响应码')),
                ('success', models.BooleanField(default=False, verbose_name='成功')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('webhook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='trading.webhook', verbose_name='Webhook')),
            ],
            options={
                'verbose_name': 'Webhook日志',
                'verbose_name_plural': 'Webhook日志',
                'ordering': ['-created_at'],
            },
        ),
    ]
