# Generated by Django 5.2.10 on 2026-01-09 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0015_add_automation_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('light', '浅色'), ('dark', '深色'), ('auto', '跟随系统')], default='light', max_length=10, verbose_name='主题')),
                ('dashboard_layout', models.JSONField(default=dict, help_text='存储用户自定义的仪表盘模块配置', verbose_name='仪表盘布局')),
                ('shortcuts_enabled', models.BooleanField(default=True, verbose_name='启用快捷键')),
                ('sidebar_collapsed', models.BooleanField(default=False, verbose_name='侧边栏收起')),
                ('notification_sound', models.BooleanField(default=True, verbose_name='通知声音')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preference', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户偏好',
                'verbose_name_plural': '用户偏好',
            },
        ),
    ]
