# Generated by Django 5.2.10 on 2026-01-09 08:52

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0016_add_user_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradelog',
            name='opening_trade',
            field=models.ForeignKey(blank=True, help_text='平仓时关联的开仓交易', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closing_trades', to='trading.tradelog', verbose_name='关联开仓'),
        ),
        migrations.AddField(
            model_name='tradelog',
            name='trade_type',
            field=models.CharField(choices=[('open', '开仓'), ('close', '平仓'), ('add', '加仓'), ('reduce', '减仓')], default='open', help_text='开仓/平仓/加仓/减仓', max_length=10, verbose_name='交易类型'),
        ),
        migrations.AlterField(
            model_name='tradelog',
            name='quantity',
            field=models.DecimalField(decimal_places=4, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='数量'),
        ),
    ]
