"""
Django settings for mytrader project.

Generated by 'django-admin startproject' using Django 5.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# 确保日志目录存在
LOGS_DIR = BASE_DIR / 'logs'
LOGS_DIR.mkdir(exist_ok=True)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# 生产环境必须设置 SECRET_KEY 环境变量
_default_secret_key = 'django-insecure-dev-only-key-do-not-use-in-production'
SECRET_KEY = os.environ.get('SECRET_KEY')
if not SECRET_KEY:
    if os.environ.get('DEBUG', '1') == '1':
        SECRET_KEY = _default_secret_key
    else:
        raise ValueError('生产环境必须设置 SECRET_KEY 环境变量')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', '1') == '1'

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_celery_beat',
    'trading',
    'quant',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mytrader.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mytrader.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Django Jazzmin 设置
JAZZMIN_SETTINGS = {
    # 主题设置
    'theme': 'forest',  # 可选: 'cerulean', 'cosmo', 'cyborg', 'darkly', 'flatly', 'journal', 'litera',
                        # 'lumen', 'lux', 'minty', 'pulse', 'sandstone', 'simplex', 'slate', 'solar',
                        # 'spacelab', 'superhero', 'united', 'yeti', 'forest'
    'theme_selector': True,  # 显示主题选择器
    'site_logo': 'img/logo.png',  # 站点logo (可选)
    'site_header': 'MyTrader 交易管理系统',
    'site_title': 'MyTrader Admin',
    'site_icon': 'img/icon.png',  # 浏览器图标 (可选)
    'welcome_sign': '欢迎来到交易管理系统',

    # 菜单设置
    'navigation': [
        {'model': 'trading.Account', 'label': '交易账户'},
        {'model': 'trading.AccountTransaction', 'label': '账户流水'},
        {'model': 'trading.Symbol', 'label': '交易标的'},
        {'model': 'trading.Strategy', 'label': '交易策略'},
        {'model': 'trading.Position', 'label': '持仓管理'},
        {'model': 'trading.TradeLog', 'label': '交易日志'},
        {'model': 'trading.TradeReview', 'label': '交易复盘'},
        {'app': 'trading', 'label': '报表分析', 'items': [
            {'model': 'trading.DailyReport'},
            {'model': 'trading.MonthlyReport'},
            {'model': 'trading.PerformanceMetrics'},
        ]},
    ],

    # 顶部菜单
    'top_menu': [
        {'app': 'trading', 'label': '交易管理'},
    ],

    # 是否显示用户详细信息
    'show_ui_builder': False,

    # 语言
    'language_chooser': False,

    # 相关模型设置
    'related_modal': False,  # 在弹出窗口中打开相关对象

    # 自定义CSS/JS
    'custom_css': None,
    'custom_js': None,

    # 显隐设置
    'hide_views': [],

    # 菜单图标 (FontAwesome)
    'icons': {
        'trading': 'fas fa-chart-line',
        'trading.Account': 'fas fa-wallet',
        'trading.AccountTransaction': 'fas fa-exchange-alt',
        'trading.Symbol': 'fas fa-tags',
        'trading.Strategy': 'fas fa-chess',
        'trading.TradeLog': 'fas fa-list-alt',
        'trading.TradeReview': 'fas fa-book-reader',
        'trading.Position': 'fas fa-balance-scale',
        'trading.DailyReport': 'fas fa-calendar-day',
        'trading.MonthlyReport': 'fas fa-calendar-alt',
        'trading.PerformanceMetrics': 'fas fa-chart-bar',
        'trading.RiskRule': 'fas fa-shield-alt',
        'trading.RiskAlert': 'fas fa-exclamation-triangle',
        'trading.RiskSnapshot': 'fas fa-camera',
        'trading.TradePlan': 'fas fa-clipboard-list',
        'trading.WatchlistGroup': 'fas fa-eye',
        'trading.WatchlistItem': 'fas fa-star',
        'trading.DailyNote': 'fas fa-sticky-note',
        'auth': 'fas fa-users',
        'auth.User': 'fas fa-user',
        'auth.Group': 'fas fa-users-cog',
        'quant': 'fas fa-robot',
        'quant.StockData': 'fas fa-database',
        'quant.QuantStrategy': 'fas fa-brain',
        'quant.BacktestResult': 'fas fa-chart-area',
        'quant.TradeOrder': 'fas fa-file-invoice-dollar',
    },

    # 列表每页显示数量
    'list_per_page': 25,

    # 是否显示多选删除按钮
    'action_builder': True,

    # 是否显示保存并添加另一个按钮
    'save_on_top': True,
}

# Celery 配置
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', 'redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Asia/Shanghai'
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

# 日志配置
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'django.log',
            'maxBytes': 10 * 1024 * 1024,  # 10MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'] if DEBUG else ['console', 'file'],
        'level': 'DEBUG' if DEBUG else 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'trading': {
            'handlers': ['console'] if DEBUG else ['console', 'file'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
        'quant': {
            'handlers': ['console'] if DEBUG else ['console', 'file'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
    },
}

# 登录URL配置
LOGIN_URL = '/admin/login/'

