"""
Django settings for mytrader project.

Generated by 'django-admin startproject' using Django 5.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-mpx9n(xem(+aul4z)*!=oi*-uvybgpck-8u-i4(-@9zxq-*=l='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'trading',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mytrader.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mytrader.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Django Jazzmin 设置
JAZZMIN_SETTINGS = {
    # 主题设置
    'theme': 'forest',  # 可选: 'cerulean', 'cosmo', 'cyborg', 'darkly', 'flatly', 'journal', 'litera',
                        # 'lumen', 'lux', 'minty', 'pulse', 'sandstone', 'simplex', 'slate', 'solar',
                        # 'spacelab', 'superhero', 'united', 'yeti', 'forest'
    'theme_selector': True,  # 显示主题选择器
    'site_logo': 'img/logo.png',  # 站点logo (可选)
    'site_header': 'MyTrader 交易管理系统',
    'site_title': 'MyTrader Admin',
    'site_icon': 'img/icon.png',  # 浏览器图标 (可选)
    'welcome_sign': '欢迎来到交易管理系统',

    # 菜单设置
    'navigation': [
        {'model': 'trading.Account', 'label': '交易账户'},
        {'model': 'trading.AccountTransaction', 'label': '账户流水'},
        {'model': 'trading.Symbol', 'label': '交易标的'},
        {'model': 'trading.Strategy', 'label': '交易策略'},
        {'model': 'trading.Position', 'label': '持仓管理'},
        {'model': 'trading.TradeLog', 'label': '交易日志'},
        {'app': 'trading', 'label': '报表分析', 'items': [
            {'model': 'trading.DailyReport'},
            {'model': 'trading.MonthlyReport'},
            {'model': 'trading.PerformanceMetrics'},
        ]},
    ],

    # 顶部菜单
    'top_menu': [
        {'app': 'trading', 'label': '交易管理'},
    ],

    # 是否显示用户详细信息
    'show_ui_builder': False,

    # 语言
    'language_chooser': False,

    # 相关模型设置
    'related_modal': False,  # 在弹出窗口中打开相关对象

    # 自定义CSS/JS
    'custom_css': None,
    'custom_js': None,

    # 显隐设置
    'hide_views': [],

    # 菜单图标 (FontAwesome)
    'icons': {
        'trading': 'fas fa-chart-line',
        'trading.Account': 'fas fa-wallet',
        'trading.AccountTransaction': 'fas fa-exchange-alt',
        'trading.Symbol': 'fas fa-tags',
        'trading.Strategy': 'fas fa-chess',
        'trading.TradeLog': 'fas fa-list-alt',
        'trading.Position': 'fas fa-balance-scale',
        'trading.DailyReport': 'fas fa-calendar-day',
        'trading.MonthlyReport': 'fas fa-calendar-alt',
        'trading.PerformanceMetrics': 'fas fa-chart-bar',
        'auth': 'fas fa-users',
        'auth.User': 'fas fa-user',
        'auth.Group': 'fas fa-users-cog',
    },

    # 列表每页显示数量
    'list_per_page': 25,

    # 是否显示多选删除按钮
    'action_builder': True,

    # 是否显示保存并添加另一个按钮
    'save_on_top': True,
}
